### ISSUE TITLE
Document viewer application for desktop

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#190] opened 2018-03-08 01:53 UTC
This issue was originally raised via forum thread:
[https://forum.groupdocs.com/t/xl20180307-ui-sample-for-desktop-app-deployment/5830](https://forum.groupdocs.com/t/xl20180307-ui-sample-for-desktop-app-deployment/5830)

One of the users requested for a sample document viewer application for the desktop.

**Comment by bobkovalex** [comment] 2019-09-25 11:29
Duplicate of **Implementation of Sample Document Viewer Application in Windows Forms** #107

**Closed by bobkovalex** 2019-09-25 11:29 UTC
Labels: duplicate
